export const LOAD_CONFIGS = "LOAD_CONFIGS";
export const LOAD_CONFIGS_SUCCESS = "LOAD_CONFIGS_SUCCESS";
export const LOAD_CONFIGS_ERROR = "LOAD_CONFIGS_ERROR";


export const UPDATE_PRIORITY = "UPDATE_PRIORITY";
export const UPDATE_PRIORITY_SUCCESS = "UPDATE_PRIORITY_SUCCESS";
export const UPDATE_PRIORITY_ERROR = "UPDATE_PRIORITY_ERROR";